package view;

import model.User;
import static model.User.logIn.Incorrect;

/**
 *
 * @author ADMIN
 */
public class GDLogin extends GD_mainStream {

    /**
     * Creates new form GDLogin
     */
    public GDLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_DangNhap = new javax.swing.JLabel();
        imageLogoUET = new javax.swing.JLabel();
        Button_DangNhap = new javax.swing.JButton();
        Label_TaiKhoan = new javax.swing.JLabel();
        Label_MatKhau = new javax.swing.JLabel();
        Field_TaiKhoan = new javax.swing.JTextField();
        Field_MatKhau = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 400));

        Label_DangNhap.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        Label_DangNhap.setText("ĐĂNG NHẬP");

        imageLogoUET.setText("jLabel5");

        Button_DangNhap.setText("Đăng nhập");
        Button_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DangNhapActionPerformed(evt);
            }
        });

        Label_TaiKhoan.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        Label_TaiKhoan.setText("Tài Khoản:");

        Label_MatKhau.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        Label_MatKhau.setText("Mật Khẩu:");

        Field_TaiKhoan.setMinimumSize(new java.awt.Dimension(70, 25));
        Field_TaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_TaiKhoanActionPerformed(evt);
            }
        });

        Field_MatKhau.setMinimumSize(new java.awt.Dimension(70, 25));
        Field_MatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_MatKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(Label_DangNhap))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_TaiKhoan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Button_DangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imageLogoUET, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(imageLogoUET)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_TaiKhoan)
                    .addComponent(Field_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_MatKhau)
                    .addComponent(Field_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_DangNhap)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Field_TaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_TaiKhoanActionPerformed
        // TODO: when type in Username 
    }//GEN-LAST:event_Field_TaiKhoanActionPerformed

    private void Button_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DangNhapActionPerformed
        // TODO: when click the Log_in_Button
        switch (currentUser.logIn(Field_TaiKhoan.getText(), String.valueOf(Field_MatKhau.getPassword()))) {
            
            case Correct: // Forward to Menu
            {
                // Khởi tạo cửa sổ Menu
                GDMenu menu = new GDMenu();
    
                // Hiển thị cửa sổ Menu
                menu.setVisible(true);

                // Ẩn cửa sổ hiện tại (tùy chọn)
                this.setVisible(false);
                
                currentUser.setID(Field_TaiKhoan.getText());
                break;
            }
            
            case First_Login:
                
            case Incorrect: // point to somewhere to create a new password.
            
            default: 
                Field_TaiKhoan.setText("Sai tai khoan hoac mat khau");
            
        }
    }//GEN-LAST:event_Button_DangNhapActionPerformed

    private void Field_MatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_MatKhauActionPerformed
        // TODO: when type in Password
    }//GEN-LAST:event_Field_MatKhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GDLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GDLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GDLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GDLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GDLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_DangNhap;
    private javax.swing.JPasswordField Field_MatKhau;
    private javax.swing.JTextField Field_TaiKhoan;
    private javax.swing.JLabel Label_DangNhap;
    private javax.swing.JLabel Label_MatKhau;
    private javax.swing.JLabel Label_TaiKhoan;
    private javax.swing.JLabel imageLogoUET;
    // End of variables declaration//GEN-END:variables
}
