package view;

import controller.LoginController;
import controller.UpdateTableMuonTraTaiLieu;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.entity.Request;


public class MuonSachJFrame extends javax.swing.JFrame {
    
    private Request currentRequest;

    /**
     * Creates new form MuonSachJFrame
     */
    public MuonSachJFrame(Request x) {
        currentRequest = x;
        
        initComponents();
        initTextField();
        
        
        documentIDTextField.setEditable(false);
        documentTitleTextField.setEditable(false);
        userIDTextField.setEditable(false);
        userNameTextField.setEditable(false);
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        
        setRequestInfo();
    }
    
    private void setRequestInfo() {
        documentIDTextField.setText(currentRequest.getDocumentID());
        documentTitleTextField.setText(currentRequest.getDocument_title());
        userIDTextField.setText(currentRequest.getUserID());
        userNameTextField.setText(currentRequest.getUser_fullName());
        borrowDateTextField.setText(currentRequest.getBorrowDate());
        if (currentRequest.getReturnDate() == null) {
            returnDateTextField.setText("Chưa trả");
            
        } else {
            returnDateTextField.setText(currentRequest.getReturnDate());
            // Khóa nút "Trả ngay" nếu yêu cầu đã được trả trước đó rồi
            returnButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBigMuonSach = new javax.swing.JPanel();
        jpnMuonSach = new javax.swing.JPanel();
        documentIDLabel = new javax.swing.JLabel();
        userIDLabel = new javax.swing.JLabel();
        documentIDTextField = new javax.swing.JTextField();
        userIDTextField = new javax.swing.JTextField();
        jButtonReset = new javax.swing.JButton();
        documentTitleLabel = new javax.swing.JLabel();
        documentTitleTextField = new javax.swing.JTextField();
        userNameLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        borrowDateLabel = new javax.swing.JLabel();
        borrowDateTextField = new javax.swing.JTextField();
        returnDateLabel = new javax.swing.JLabel();
        returnDateTextField = new javax.swing.JTextField();
        returnButton = new javax.swing.JButton();
        jButtonLuuThongTin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBigMuonSach.setBackground(new java.awt.Color(214, 239, 216));

        jpnMuonSach.setBackground(new java.awt.Color(128, 175, 129));
        jpnMuonSach.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phiếu mượn trả", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        documentIDLabel.setBackground(new java.awt.Color(255, 255, 255));
        documentIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        documentIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        documentIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        documentIDLabel.setText("Mã tài liệu:");

        userIDLabel.setBackground(new java.awt.Color(255, 255, 255));
        userIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        userIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userIDLabel.setText("Mã người dùng:");

        jButtonReset.setBackground(new java.awt.Color(80, 141, 78));
        jButtonReset.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jButtonReset.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReset.setText("Reset");
        jButtonReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonResetMouseClicked(evt);
            }
        });

        documentTitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        documentTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        documentTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        documentTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        documentTitleLabel.setText("Tiêu đề sách:");

        userNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        userNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userNameLabel.setText("Tên người dùng:");

        borrowDateLabel.setBackground(new java.awt.Color(255, 255, 255));
        borrowDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        borrowDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        borrowDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        borrowDateLabel.setText("Ngày mượn:");

        returnDateLabel.setBackground(new java.awt.Color(255, 255, 255));
        returnDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        returnDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        returnDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        returnDateLabel.setText("Ngày trả:");

        returnButton.setBackground(new java.awt.Color(80, 141, 78));
        returnButton.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        returnButton.setForeground(new java.awt.Color(255, 255, 255));
        returnButton.setText("Trả ngay");
        returnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonMouseClicked(evt);
            }
        });

        jButtonLuuThongTin.setBackground(new java.awt.Color(80, 141, 78));
        jButtonLuuThongTin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLuuThongTin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLuuThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logoSaveAS.png"))); // NOI18N
        jButtonLuuThongTin.setText("Lưu thông tin");
        jButtonLuuThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLuuThongTinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnMuonSachLayout = new javax.swing.GroupLayout(jpnMuonSach);
        jpnMuonSach.setLayout(jpnMuonSachLayout);
        jpnMuonSachLayout.setHorizontalGroup(
            jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMuonSachLayout.createSequentialGroup()
                .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnMuonSachLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(documentIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(borrowDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(documentTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(returnDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(documentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(documentTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(borrowDateTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpnMuonSachLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButtonLuuThongTin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(returnButton)))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jpnMuonSachLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {borrowDateLabel, documentIDLabel, documentTitleLabel, returnDateLabel, userIDLabel, userNameLabel});

        jpnMuonSachLayout.setVerticalGroup(
            jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMuonSachLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(documentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(documentIDLabel))
                .addGap(18, 18, 18)
                .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(documentTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(documentTitleLabel))
                .addGap(23, 23, 23)
                .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIDLabel))
                .addGap(21, 21, 21)
                .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameLabel))
                .addGap(26, 26, 26)
                .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrowDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrowDateLabel))
                .addGap(18, 18, 18)
                .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnDateLabel))
                .addGap(18, 18, 18)
                .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonLuuThongTin)
                        .addGroup(jpnMuonSachLayout.createSequentialGroup()
                            .addComponent(jButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(2, 2, 2)))
                    .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jpnMuonSachLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {borrowDateLabel, documentIDLabel, documentTitleLabel, returnDateLabel, userIDLabel, userNameLabel});

        documentIDLabel.getAccessibleContext().setAccessibleName("");
        userIDLabel.getAccessibleContext().setAccessibleName("");
        documentTitleLabel.getAccessibleContext().setAccessibleName("");
        userNameLabel.getAccessibleContext().setAccessibleName("");
        borrowDateLabel.getAccessibleContext().setAccessibleName("");
        returnDateLabel.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanelBigMuonSachLayout = new javax.swing.GroupLayout(jPanelBigMuonSach);
        jPanelBigMuonSach.setLayout(jPanelBigMuonSachLayout);
        jPanelBigMuonSachLayout.setHorizontalGroup(
            jPanelBigMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBigMuonSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnMuonSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBigMuonSachLayout.setVerticalGroup(
            jPanelBigMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBigMuonSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnMuonSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        jpnMuonSach.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBigMuonSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBigMuonSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initTextField() {
        documentIDTextField.setEditable(false);
        documentTitleTextField.setEditable(false);
        userIDTextField.setEditable(false);
        userNameTextField.setEditable(false);
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        
        if (!(LoginController.getAcc() instanceof model.entity.Staff)) {
            returnDateTextField.setEditable(false);
            borrowDateTextField.setEditable(false);
        }
    }
    
    private void returnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseClicked

        Request org = new Request(currentRequest);
        
        if (evt.getClickCount() > 0 && returnButton.isEnabled()) {     
            try {
                // Chỉnh ngày mượn theo thông tin được nhập
                currentRequest.setBorrowDate(borrowDateTextField.getText());
                UpdateTableMuonTraTaiLieu.getInstance().updateElement(currentRequest);
                
                // Chỉnh ngày trả là hôm nay
                UpdateTableMuonTraTaiLieu.getInstance().returnRequest(currentRequest);
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                this.dispose();
                
            } catch (SQLException ex) {
                Logger.getLogger(MuonSachJFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage());
                currentRequest.setBorrowDate(org.getBorrowDate());
                currentRequest.setReturnDate(org.getReturnDate());
            }
        }
    }//GEN-LAST:event_returnButtonMouseClicked

    private void jButtonResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonResetMouseClicked

        if (evt.getClickCount() > 0) {
            setRequestInfo();
        }
    }//GEN-LAST:event_jButtonResetMouseClicked

    private void jButtonLuuThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLuuThongTinMouseClicked

        Request org = new Request(currentRequest);
        
        try {
            String s = borrowDateTextField.getText();
            currentRequest.setBorrowDate(s);
            s = returnDateTextField.getText();
            if (!s.replace("Chưa trả", "").trim().equals("")) {
                currentRequest.setReturnDate(s);
                model.dao.RequestDAO.updateDateRequest(currentRequest);
                
            } else {
                JOptionPane.showMessageDialog(this, "Xác nhận không thực hiện yêu cầu cập nhật");
            }

            this.dispose();
                
        } catch (SQLException ex) {
            Logger.getLogger(MuonSachJFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
            currentRequest.setBorrowDate(org.getBorrowDate());
            currentRequest.setReturnDate(org.getReturnDate());
        }
    }//GEN-LAST:event_jButtonLuuThongTinMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel borrowDateLabel;
    private javax.swing.JTextField borrowDateTextField;
    private javax.swing.JLabel documentIDLabel;
    private javax.swing.JTextField documentIDTextField;
    private javax.swing.JLabel documentTitleLabel;
    private javax.swing.JTextField documentTitleTextField;
    private javax.swing.JButton jButtonLuuThongTin;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JPanel jPanelBigMuonSach;
    private javax.swing.JPanel jpnMuonSach;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel returnDateLabel;
    private javax.swing.JTextField returnDateTextField;
    private javax.swing.JLabel userIDLabel;
    private javax.swing.JTextField userIDTextField;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
