/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ADMIN
 */
public class MuonSachJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MuonSachJFrame
     */
    public MuonSachJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBigMuonSach = new javax.swing.JPanel();
        jpnMuonSach = new javax.swing.JPanel();
        jlbDocumentID = new javax.swing.JLabel();
        jlbRequestID = new javax.swing.JLabel();
        jlbUserID = new javax.swing.JLabel();
        jlbquantityBorrow = new javax.swing.JLabel();
        JTextFieldDocumentID = new javax.swing.JTextField();
        jTextFieldRequestID = new javax.swing.JTextField();
        jTextFieldUserID = new javax.swing.JTextField();
        jTextQuantityBorrow = new javax.swing.JTextField();
        jButtonReset = new javax.swing.JButton();
        jButtonLuuThongTin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBigMuonSach.setBackground(new java.awt.Color(214, 239, 216));

        jpnMuonSach.setBackground(new java.awt.Color(128, 175, 129));
        jpnMuonSach.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mượn sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        jlbDocumentID.setBackground(new java.awt.Color(255, 255, 255));
        jlbDocumentID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbDocumentID.setForeground(new java.awt.Color(255, 255, 255));
        jlbDocumentID.setText("documentID:");

        jlbRequestID.setBackground(new java.awt.Color(255, 255, 255));
        jlbRequestID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbRequestID.setForeground(new java.awt.Color(255, 255, 255));
        jlbRequestID.setText("requestID:");

        jlbUserID.setBackground(new java.awt.Color(255, 255, 255));
        jlbUserID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbUserID.setForeground(new java.awt.Color(255, 255, 255));
        jlbUserID.setText("userID:");

        jlbquantityBorrow.setBackground(new java.awt.Color(255, 255, 255));
        jlbquantityBorrow.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbquantityBorrow.setForeground(new java.awt.Color(255, 255, 255));
        jlbquantityBorrow.setText("quantityBorrow:");

        jButtonReset.setBackground(new java.awt.Color(80, 141, 78));
        jButtonReset.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jButtonReset.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnMuonSachLayout = new javax.swing.GroupLayout(jpnMuonSach);
        jpnMuonSach.setLayout(jpnMuonSachLayout);
        jpnMuonSachLayout.setHorizontalGroup(
            jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMuonSachLayout.createSequentialGroup()
                .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnMuonSachLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnMuonSachLayout.createSequentialGroup()
                                .addComponent(jlbDocumentID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JTextFieldDocumentID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnMuonSachLayout.createSequentialGroup()
                                    .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jlbUserID)
                                        .addComponent(jlbRequestID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldUserID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldRequestID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnMuonSachLayout.createSequentialGroup()
                                    .addComponent(jlbquantityBorrow)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextQuantityBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jpnMuonSachLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButtonReset)))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        jpnMuonSachLayout.setVerticalGroup(
            jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMuonSachLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbDocumentID)
                    .addComponent(JTextFieldDocumentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbRequestID)
                    .addComponent(jTextFieldRequestID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbUserID)
                    .addComponent(jTextFieldUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jpnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbquantityBorrow)
                    .addComponent(jTextQuantityBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonReset)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jButtonLuuThongTin.setBackground(new java.awt.Color(80, 141, 78));
        jButtonLuuThongTin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLuuThongTin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLuuThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logoSaveAS.png"))); // NOI18N
        jButtonLuuThongTin.setText("Lưu thông tin");

        javax.swing.GroupLayout jPanelBigMuonSachLayout = new javax.swing.GroupLayout(jPanelBigMuonSach);
        jPanelBigMuonSach.setLayout(jPanelBigMuonSachLayout);
        jPanelBigMuonSachLayout.setHorizontalGroup(
            jPanelBigMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBigMuonSachLayout.createSequentialGroup()
                .addGroup(jPanelBigMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBigMuonSachLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLuuThongTin))
                    .addGroup(jPanelBigMuonSachLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jpnMuonSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        jPanelBigMuonSachLayout.setVerticalGroup(
            jPanelBigMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBigMuonSachLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jButtonLuuThongTin)
                .addGap(15, 15, 15)
                .addComponent(jpnMuonSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jpnMuonSach.getAccessibleContext().setAccessibleName("Mượn sách");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBigMuonSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBigMuonSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        JTextFieldDocumentID.setText("");
        jTextQuantityBorrow.setText("");
        jTextFieldRequestID.setText("");
        jTextFieldUserID.setText("");
    }//GEN-LAST:event_jButtonResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MuonSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MuonSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MuonSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MuonSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MuonSachJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextFieldDocumentID;
    private javax.swing.JButton jButtonLuuThongTin;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JPanel jPanelBigMuonSach;
    private javax.swing.JTextField jTextFieldRequestID;
    private javax.swing.JTextField jTextFieldUserID;
    private javax.swing.JTextField jTextQuantityBorrow;
    private javax.swing.JLabel jlbDocumentID;
    private javax.swing.JLabel jlbRequestID;
    private javax.swing.JLabel jlbUserID;
    private javax.swing.JLabel jlbquantityBorrow;
    private javax.swing.JPanel jpnMuonSach;
    // End of variables declaration//GEN-END:variables
}
