/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.UpdateTableTaiLieu;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class TaiLieuPanel extends javax.swing.JPanel {

    /**
     * Creates new form TaiLieuPanel
     */
    public TaiLieuPanel() {
        initComponents();
        initTableTaiLieu();
        UpdateTableTaiLieu ctrl = UpdateTableTaiLieu.getInstance();
        try {
            ctrl.setTableUpToDate(jTableThongTinTaiLieu, ButtonThemTaiLieu, JTextFieldTimKiemTaiLieu);
            
        } catch (SQLException | IOException ex) {
            Logger.getLogger(TaiLieuPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnViewTaiLieu = new javax.swing.JPanel();
        JTextFieldTimKiemTaiLieu = new javax.swing.JTextField();
        jLabelTimKiem = new javax.swing.JLabel();
        ButtonThemTaiLieu = new javax.swing.JButton();
        jScrollPaneTaiLieu = new javax.swing.JScrollPane();
        jTableThongTinTaiLieu = new javax.swing.JTable();

        jpnViewTaiLieu.setBackground(new java.awt.Color(128, 175, 129));
        jpnViewTaiLieu.setPreferredSize(new java.awt.Dimension(945, 501));

        JTextFieldTimKiemTaiLieu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTextFieldTimKiemTaiLieuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTextFieldTimKiemTaiLieuFocusLost(evt);
            }
        });
        JTextFieldTimKiemTaiLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldTimKiemTaiLieuActionPerformed(evt);
            }
        });

        jLabelTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LogoTimKiem.png"))); // NOI18N

        ButtonThemTaiLieu.setBackground(new java.awt.Color(80, 141, 78));
        ButtonThemTaiLieu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonThemTaiLieu.setForeground(new java.awt.Color(255, 255, 255));
        ButtonThemTaiLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LogoThemTaiLieu.png"))); // NOI18N
        ButtonThemTaiLieu.setText("Thêm tài liệu");
        ButtonThemTaiLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonThemTaiLieuActionPerformed(evt);
            }
        });

        jTableThongTinTaiLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tiêu đề", "Tác giả", "Nhà xuất bản", "Năm xuất bản", "Thể loại", "Ngôn ngữ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableThongTinTaiLieu.setColumnSelectionAllowed(true);
        jTableThongTinTaiLieu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableThongTinTaiLieu.setMinimumSize(new java.awt.Dimension(200, 0));
        jScrollPaneTaiLieu.setViewportView(jTableThongTinTaiLieu);
        jTableThongTinTaiLieu.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jpnViewTaiLieuLayout = new javax.swing.GroupLayout(jpnViewTaiLieu);
        jpnViewTaiLieu.setLayout(jpnViewTaiLieuLayout);
        jpnViewTaiLieuLayout.setHorizontalGroup(
            jpnViewTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnViewTaiLieuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTextFieldTimKiemTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(ButtonThemTaiLieu)
                .addGap(30, 30, 30))
            .addGroup(jpnViewTaiLieuLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPaneTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnViewTaiLieuLayout.setVerticalGroup(
            jpnViewTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnViewTaiLieuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpnViewTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonThemTaiLieu)
                    .addComponent(JTextFieldTimKiemTaiLieu))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnViewTaiLieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnViewTaiLieu, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JTextFieldTimKiemTaiLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldTimKiemTaiLieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldTimKiemTaiLieuActionPerformed

    private void ButtonThemTaiLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonThemTaiLieuActionPerformed
        ThemTaiLieuFrame themTaiLieuFrame = new ThemTaiLieuFrame();
        themTaiLieuFrame.setVisible(true);
    }//GEN-LAST:event_ButtonThemTaiLieuActionPerformed

    private void JTextFieldTimKiemTaiLieuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTextFieldTimKiemTaiLieuFocusGained
        // TODO add your handling code here:
        JTextFieldTimKiemTaiLieu.setText("");
        JTextFieldTimKiemTaiLieu.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14)); // Đặt phông là Segoe UI, kích thước 14
        JTextFieldTimKiemTaiLieu.setForeground(java.awt.Color.BLACK); // Đặt màu chữ là đen
    }//GEN-LAST:event_JTextFieldTimKiemTaiLieuFocusGained

    private void JTextFieldTimKiemTaiLieuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTextFieldTimKiemTaiLieuFocusLost
        // TODO add your handling code here:
        if(JTextFieldTimKiemTaiLieu.getText().equals("")) {
            JTextFieldTimKiemTaiLieu.setText("Tìm kiếm thông tin thành viên");
            JTextFieldTimKiemTaiLieu.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14)); // Đặt phông là Segoe UI, kích thước 14
            JTextFieldTimKiemTaiLieu.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_JTextFieldTimKiemTaiLieuFocusLost

    private void initTableTaiLieu() {
        jTableThongTinTaiLieu.getTableHeader().setFont(new Font("Arrial", Font.BOLD, 14));
        jTableThongTinTaiLieu.getTableHeader().setForeground(Color.white);
        jTableThongTinTaiLieu.getTableHeader().setPreferredSize(new Dimension(100,50));
        jTableThongTinTaiLieu.getTableHeader().setBackground(new Color(80,141,78));
        jTableThongTinTaiLieu.setRowHeight(40);
        jTableThongTinTaiLieu.validate();
        jTableThongTinTaiLieu.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonThemTaiLieu;
    private javax.swing.JTextField JTextFieldTimKiemTaiLieu;
    private javax.swing.JLabel jLabelTimKiem;
    private javax.swing.JScrollPane jScrollPaneTaiLieu;
    private javax.swing.JTable jTableThongTinTaiLieu;
    private javax.swing.JPanel jpnViewTaiLieu;
    // End of variables declaration//GEN-END:variables
}
