/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.UpdateTableTaiLieu;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.dao.FileFormatException;
import model.entity.Book;

/**
 *
 * @author HP
 */
public class ThemTaiLieuFrame extends javax.swing.JFrame {

    /**
     * Creates new form ThemTaiLieuFrame
     */
    public ThemTaiLieuFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public ThemTaiLieuFrame(String id, String title, String author, String publisher, String publicationYear, String category, String language, String summary, String fileImage) {
    // Khởi tạo giao diện
        initComponents();

        // Gán giá trị vào các JTextField
        jTextAreaTomTat.setText(summary);
        jTextFieldBookAuthor.setText(author);
        jTextFieldBookID.setText(id);
        jTextFieldBookPublisher.setText(publisher);
        jTextFieldBookTitle.setText(title);
        jTextFieldCategory.setText(category);
        jTextFieldLanguage.setText(language);
        jTextFieldPublicationYear.setText(publicationYear);

        // Đặt trường ID không thể chỉnh sửa
        jTextFieldBookID.setEditable(false);

        // Cài đặt chế độ đóng cửa sổ
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnViewThemTaiLieu = new javax.swing.JPanel();
        jpnThemTaiLieu = new javax.swing.JPanel();
        jlbID = new javax.swing.JLabel();
        jlbTitle = new javax.swing.JLabel();
        jlbAuthor = new javax.swing.JLabel();
        jlbCategory = new javax.swing.JLabel();
        jlbPublicationYear = new javax.swing.JLabel();
        jlbPublisher = new javax.swing.JLabel();
        ButtonReset = new javax.swing.JButton();
        jTextFieldBookTitle = new javax.swing.JTextField();
        jTextFieldBookID = new javax.swing.JTextField();
        jTextFieldBookAuthor = new javax.swing.JTextField();
        jTextFieldBookPublisher = new javax.swing.JTextField();
        jTextFieldPublicationYear = new javax.swing.JTextField();
        jTextFieldCategory = new javax.swing.JTextField();
        jlbLanguage = new javax.swing.JLabel();
        jlbSummary = new javax.swing.JLabel();
        jTextFieldLanguage = new javax.swing.JTextField();
        jlbImage = new javax.swing.JLabel();
        jButtonChonFileAnh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaTomTat = new javax.swing.JTextArea();
        ButtonSaveBook = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpnViewThemTaiLieu.setBackground(new java.awt.Color(214, 239, 216));

        jpnThemTaiLieu.setBackground(new java.awt.Color(128, 175, 129));
        jpnThemTaiLieu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin tài liệu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jpnThemTaiLieu.setForeground(new java.awt.Color(255, 255, 255));
        jpnThemTaiLieu.setName(""); // NOI18N

        jlbID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbID.setForeground(new java.awt.Color(255, 255, 255));
        jlbID.setText("ID:         ");

        jlbTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbTitle.setForeground(new java.awt.Color(255, 255, 255));
        jlbTitle.setText("Tiêu đề:");

        jlbAuthor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbAuthor.setForeground(new java.awt.Color(255, 255, 255));
        jlbAuthor.setText("Tác giả:");

        jlbCategory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbCategory.setForeground(new java.awt.Color(255, 255, 255));
        jlbCategory.setText("Thể loại:");

        jlbPublicationYear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbPublicationYear.setForeground(new java.awt.Color(255, 255, 255));
        jlbPublicationYear.setText("Năm xuất bản:");

        jlbPublisher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbPublisher.setForeground(new java.awt.Color(255, 255, 255));
        jlbPublisher.setText("Nhà xuất bản:");

        ButtonReset.setBackground(new java.awt.Color(80, 141, 78));
        ButtonReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonReset.setForeground(new java.awt.Color(255, 255, 255));
        ButtonReset.setText("Reset");
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });

        jTextFieldBookPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBookPublisherActionPerformed(evt);
            }
        });

        jlbLanguage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbLanguage.setForeground(new java.awt.Color(255, 255, 255));
        jlbLanguage.setText("Ngôn ngữ:");

        jlbSummary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbSummary.setForeground(new java.awt.Color(255, 255, 255));
        jlbSummary.setText("Tóm tắt:");

        jlbImage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbImage.setForeground(new java.awt.Color(255, 255, 255));
        jlbImage.setText("Hình ảnh:");

        jButtonChonFileAnh.setBackground(new java.awt.Color(204, 204, 204));
        jButtonChonFileAnh.setText("Chọn file ảnh");
        jButtonChonFileAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChonFileAnhActionPerformed(evt);
            }
        });

        jTextAreaTomTat.setColumns(20);
        jTextAreaTomTat.setRows(5);
        jScrollPane2.setViewportView(jTextAreaTomTat);

        javax.swing.GroupLayout jpnThemTaiLieuLayout = new javax.swing.GroupLayout(jpnThemTaiLieu);
        jpnThemTaiLieu.setLayout(jpnThemTaiLieuLayout);
        jpnThemTaiLieuLayout.setHorizontalGroup(
            jpnThemTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThemTaiLieuLayout.createSequentialGroup()
                .addGroup(jpnThemTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnThemTaiLieuLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jpnThemTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbLanguage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbPublisher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbPublicationYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnThemTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldLanguage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTextFieldCategory, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPublicationYear, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBookPublisher, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBookAuthor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBookID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBookTitle, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jpnThemTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnThemTaiLieuLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnThemTaiLieuLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(jpnThemTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlbImage)
                                    .addComponent(jlbSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonChonFileAnh))))
                    .addGroup(jpnThemTaiLieuLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(ButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnThemTaiLieuLayout.setVerticalGroup(
            jpnThemTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThemTaiLieuLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jpnThemTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnThemTaiLieuLayout.createSequentialGroup()
                        .addGroup(jpnThemTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jpnThemTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jpnThemTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonChonFileAnh))
                        .addGap(15, 15, 15)
                        .addGroup(jpnThemTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBookPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jpnThemTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbPublicationYear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPublicationYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnThemTaiLieuLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jpnThemTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jpnThemTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addComponent(ButtonReset)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        ButtonSaveBook.setBackground(new java.awt.Color(80, 141, 78));
        ButtonSaveBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonSaveBook.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSaveBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logoSaveAS.png"))); // NOI18N
        ButtonSaveBook.setText("Lưu dữ liệu");
        ButtonSaveBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnViewThemTaiLieuLayout = new javax.swing.GroupLayout(jpnViewThemTaiLieu);
        jpnViewThemTaiLieu.setLayout(jpnViewThemTaiLieuLayout);
        jpnViewThemTaiLieuLayout.setHorizontalGroup(
            jpnViewThemTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnViewThemTaiLieuLayout.createSequentialGroup()
                .addContainerGap(753, Short.MAX_VALUE)
                .addComponent(ButtonSaveBook)
                .addContainerGap())
            .addComponent(jpnThemTaiLieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnViewThemTaiLieuLayout.setVerticalGroup(
            jpnViewThemTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnViewThemTaiLieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonSaveBook, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnThemTaiLieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnThemTaiLieu.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnViewThemTaiLieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnViewThemTaiLieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
       clearInputFields();
    }//GEN-LAST:event_ButtonResetActionPerformed

    private void jTextFieldBookPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBookPublisherActionPerformed

    }//GEN-LAST:event_jTextFieldBookPublisherActionPerformed

    private void ButtonSaveBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveBookActionPerformed
            // TODO add your handling code here:
            
        Book prototype = new Book("", "", 100, "", "", 2000, "", "", "");
             // Lấy dữ liệu từ các trường nhập liệu
        String id = jTextFieldBookID.getText();
        String title = jTextFieldBookTitle.getText();
        String author = jTextFieldBookAuthor.getText();
        String publisher = jTextFieldBookPublisher.getText();
        int publicationYear;
        String category = jTextFieldCategory.getText();
        String language = jTextFieldLanguage.getText();
        String summary = jTextAreaTomTat.getText();
        
        File fileImage = ChonFileAnhJFrame.getFileImage();
        try {
            prototype.setCover(fileImage);
            
        } catch (FileFormatException | IOException ex) {
            Logger.getLogger(ThemTaiLieuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Kiểm tra các trường bắt buộc không được để trống
        if (id.isEmpty() || title.isEmpty() || author.isEmpty() || jTextFieldPublicationYear.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin bắt buộc!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        publicationYear = Integer.parseInt(jTextFieldPublicationYear.getText());

        
        

        try {
            // Tạo đối tượng Document từ dữ liệu nhập
            Book newDocument = new Book(id, title, 100, author, publisher, publicationYear, summary, category, language);
            newDocument.setCover(prototype.getCover(), prototype.getCoverFormat());
            
            // Gọi phương thức thêm Document vào cơ sở dữ liệu
            boolean isSaved = UpdateTableTaiLieu.getInstance().addElement(newDocument);

            if (isSaved) {
                // Hiển thị thông báo thành công
                JOptionPane.showMessageDialog(this, "Thêm tài liệu mới thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

                // Xóa các trường nhập liệu để chuẩn bị cho lần nhập tiếp theo
                clearInputFields();
            } else {
                // Hiển thị thông báo lỗi
                JOptionPane.showMessageDialog(this, "Thêm tài liệu thất bại! Vui lòng kiểm tra lại.", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException | IOException | FileFormatException ex) {
            // Xử lý ngoại lệ nếu có lỗi khi thao tác với cơ sở dữ liệu
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(ThemTaiLieuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonSaveBookActionPerformed

    private void jButtonChonFileAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChonFileAnhActionPerformed
        // TODO add your handling code here:
        ChonFileAnhJFrame chonFile = new ChonFileAnhJFrame();
        chonFile.setVisible(true);
    }//GEN-LAST:event_jButtonChonFileAnhActionPerformed

    private void clearInputFields() {
        jTextAreaTomTat.setText("");
        jTextFieldBookAuthor.setText("");
        jTextFieldBookID.setText("");
        jTextFieldBookPublisher.setText("");
        jTextFieldBookTitle.setText("");
        jTextFieldCategory.setText("");
        jTextFieldLanguage.setText("");
        jTextFieldPublicationYear.setText("");
}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonReset;
    private javax.swing.JButton ButtonSaveBook;
    private javax.swing.JButton jButtonChonFileAnh;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaTomTat;
    private javax.swing.JTextField jTextFieldBookAuthor;
    private javax.swing.JTextField jTextFieldBookID;
    private javax.swing.JTextField jTextFieldBookPublisher;
    private javax.swing.JTextField jTextFieldBookTitle;
    private javax.swing.JTextField jTextFieldCategory;
    private javax.swing.JTextField jTextFieldLanguage;
    private javax.swing.JTextField jTextFieldPublicationYear;
    private javax.swing.JLabel jlbAuthor;
    private javax.swing.JLabel jlbCategory;
    private javax.swing.JLabel jlbID;
    private javax.swing.JLabel jlbImage;
    private javax.swing.JLabel jlbLanguage;
    private javax.swing.JLabel jlbPublicationYear;
    private javax.swing.JLabel jlbPublisher;
    private javax.swing.JLabel jlbSummary;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JPanel jpnThemTaiLieu;
    private javax.swing.JPanel jpnViewThemTaiLieu;
    // End of variables declaration//GEN-END:variables
}
